# Generated by Django 4.1.13 on 2024-03-31 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("lmsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookswithusers",
            name="book",
        ),
        migrations.AddField(
            model_name="bookswithusers",
            name="book",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="lmsapp.book",
            ),
            preserve_default=False,
        ),
    ]
