# Generated by Django 4.1.13 on 2024-03-31 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lmsapp", "0002_remove_bookswithusers_book_bookswithusers_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="Bookswithusers",
        ),
    ]
