# Generated by Django 4.1.13 on 2024-03-31 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lmsapp", "0005_alter_booklending_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booklending",
            name="user",
        ),
    ]
