# Generated by Django 4.1.13 on 2024-03-31 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lmsapp", "0006_remove_booklending_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booklending",
            name="book",
            field=models.ForeignKey(
                default="abc",
                on_delete=django.db.models.deletion.CASCADE,
                to="lmsapp.book",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booklending",
            name="user",
            field=models.ForeignKey(
                default="a",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="booklending",
            unique_together={("user", "book")},
        ),
    ]
